#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/kernel/.env"
COMPOSE_FILE="$SCRIPT_DIR/kernel/docker-compose.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[jodo]${NC} $1"; }
ok()    { echo -e "${GREEN}[jodo]${NC} $1"; }
warn()  { echo -e "${YELLOW}[jodo]${NC} $1"; }
err()   { echo -e "${RED}[jodo]${NC} $1" >&2; }

generate_password() {
  openssl rand -base64 24 | tr -d '/+=' | head -c 32
}

cmd_setup() {
  info "Setting up Jodo..."
  echo ""

  if [ -f "$ENV_FILE" ]; then
    warn ".env already exists at $ENV_FILE"
    read -rp "Overwrite? (y/N): " confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
      info "Setup cancelled."
      exit 0
    fi
  fi

  # Generate secrets
  ENCRYPTION_KEY=$(openssl rand -base64 32)
  DB_PASSWORD=$(generate_password)

  cat > "$ENV_FILE" << EOF
# Jodo Kernel Environment
# Generated by jodo.sh setup on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Encryption key for API keys and secrets stored in the database.
# DO NOT lose this key — encrypted data becomes unrecoverable without it.
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# PostgreSQL credentials
DB_HOST=postgres
DB_PORT=5432
DB_USER=jodo
DB_NAME=jodo_kernel
JODO_DB_PASSWORD=${DB_PASSWORD}
EOF

  echo ""
  ok "Environment file created at $ENV_FILE"
  ok "Encryption key and database password generated."
  echo ""
  info "Next steps:"
  echo "  1. cd kernel && docker-compose up -d"
  echo "  2. Open http://localhost:8080 in your browser"
  echo "  3. Complete the setup wizard"
  echo ""
}

cmd_start() {
  if [ ! -f "$ENV_FILE" ]; then
    err "No .env file found. Run './jodo.sh setup' first."
    exit 1
  fi
  info "Starting Jodo..."
  cd "$SCRIPT_DIR/kernel"
  docker compose up -d
  ok "Jodo is starting. Open http://localhost:8080"
}

cmd_stop() {
  info "Stopping Jodo..."
  cd "$SCRIPT_DIR/kernel"
  docker compose down
  ok "Jodo stopped."
}

cmd_logs() {
  cd "$SCRIPT_DIR/kernel"
  docker compose logs -f kernel
}

cmd_help() {
  echo "Usage: ./jodo.sh <command>"
  echo ""
  echo "Commands:"
  echo "  setup    Generate .env file with encryption key and database password"
  echo "  start    Start Jodo (docker-compose up)"
  echo "  stop     Stop Jodo (docker-compose down)"
  echo "  logs     Follow kernel logs"
  echo "  help     Show this help message"
  echo ""
}

case "${1:-help}" in
  setup) cmd_setup ;;
  start) cmd_start ;;
  stop)  cmd_stop  ;;
  logs)  cmd_logs  ;;
  help)  cmd_help  ;;
  *)     err "Unknown command: $1"; cmd_help; exit 1 ;;
esac
